### ISSUE TITLE
starligh tailwind(?) styling for active multiSidebar tab

### ISSUE THREAD

**Issue by Freymaurer** [lorenzolewis/starlight-utils#114]
Hey man! i really like the multi sidebar but i have some minor issues

Not sure why this happens for me (maybe because i use starlight with tailwind), but for me the active tab looks like this:

![image](https://github.com/user-attachments/assets/4cb89868-4cf3-4f40-aad9-f645550aef23)

Which can be resolved by modifying this part:

https://github.com/lorenzolewis/starlight-utils/blob/a185830d0185fb7d8bb08685f0d649c89174feca/packages/starlight-utils/components/HorizontalList.astro#L95

```diff
.tab > [role="tab"] {
    display: block;
    text-align: center;
    font-size: var(--sl-text-base);
    font-weight: 400;
    text-decoration: none;
    color: var(--sl-color-gray-2);
    border-bottom: 1px solid var(--sl-color-gray-5);
+   border-top: unset;
+   border-left: unset;
+   border-right: unset;
    padding-inline: 0.2rem;
  }
```

I was able to fix this on my end using a custom.css and:

```css
.tab > [role="tab"] {
  border-width: 1px !important;
  border-top: unset !important;
  border-left: unset !important;
  border-right: unset !important;
}
```
